apiVersion: v1
kind: Secret
metadata:
  name: mlflow-postgres-secret
  namespace: mlflow
  labels:
    app: mlflow-deployment
type: Opaque
stringData:
  POSTGRES_USER: sdg-user
  POSTGRES_PASSWORD: sdg-password
  POSTGRES_DB: mlflow-postgres
---

