apiVersion: v1
kind: Service
metadata:
  name: mlflow-postgres-service
  namespace: mlflow
  labels:
    svc: mlflow-postgres-service
spec:
  selector:
    app: mlflow-postgres
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
---
